### ISSUE TITLE
Next.JS not working: Cannot read properties of undefined (reading 'className')

### ISSUE THREAD

**Issue by Jesper-Hustad** [andreaswilli/react-verification-input#148]
Using Next.JS 15.0.1

```
intercept-console-error.js:45 TypeError: Cannot read properties of undefined (reading 'className')
    at VerificationInput (index.js:2:7037)
    at react-stack-bottom-frame (react-dom-client.development.js:22349:20)
    at renderWithHooks (react-dom-client.development.js:5740:22)
    at updateForwardRef (react-dom-client.development.js:7745:19)
    at beginWork (react-dom-client.development.js:9997:18)
    at runWithFiberInDEV (react-dom-client.development.js:544:16)
    at performUnitOfWork (react-dom-client.development.js:14997:22)
    at workLoopSync (react-dom-client.development.js:14827:41)
    at renderRootSync (react-dom-client.development.js:14807:11)
    at performWorkOnRoot (react-dom-client.development.js:14342:44)
    at performWorkOnRootViaSchedulerTask (react-dom-client.development.js:15853:7)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:44:48)

The above error occurred in the <NotFoundErrorBoundary> component.

React will try to recreate this component tree from scratch using the error boundary you provided, ReactDevOverlay.
```

I may be using some wrong settings or similar, but could not fix this issue.

Tried putting an empty className prop.

Also tried installing again with npm and installing an older version of the library with NPM

**Comment by andreaswilli** [comment]
Thanks for the report. The issue was the library relying on `defualtProps` which was removed in React 19 (Next already uses React 19 RC).

Should be fixed in `4.1.3`.
